import 'package:get/get.dart';
import 'package:yannyamba/core/utils/constants/app_texts.dart';

class AppLocalizations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      AppText.phoneNumber: 'Phone Number',
      AppText.logIn: 'Log In',
      AppText.createAccount: 'Create Account',
      AppText.dontHaveAnAccount: "Don't have an account? ",
      AppText.alreadyHaveAnAccount: "Already have an account? ",
      AppText.signUp: 'Sign Up',
      AppText.signIn: 'Sign In',
      AppText.settings: 'Settings',
      AppText.switchToOwnersDashboard: 'Switch to Owners dashboard',
      AppText.profile: 'Profile',
      AppText.language: 'Language',
      AppText.notificationSettings: 'Notification Settings',
      AppText.contactUs: 'Contact us',
      AppText.faq: 'FAQ',
      AppText.goodMorning: 'Good Morning!',
      AppText.noFurnishedApartmentsFound: 'No furnished apartments found',
      AppText.tryAdjustingYourFilters: 'Try adjusting your filters',
      AppText.normalApartments: 'Normal Apartments',
      AppText.longTermRentals: 'Long-term Rentals',
      AppText.monthlyPayments: 'Monthly payments',
      AppText.homeAndOfficeSpaces: 'Home & Office spaces',
      AppText.explore: 'Explore',
      AppText.logInToGetAccess: 'Log in to get access to all the features',
      AppText.haventAccountAlready: "Haven't account already?",
      AppText.createAnAccount: 'Create an account',
      AppText.unableToLoadProfile: 'Unable to load profile',
      AppText.retry: 'Retry',
      AppText.noProfileInfoAvailable: 'No profile information available',
      AppText.referenceContacts: 'Reference Contacts',
      AppText.contactName: 'Contact Name',
      AppText.primaryContact: 'Primary Contact',
      AppText.contactOwner: 'Contact Owner',
      AppText.iWantToRent: 'I Want to Rent',
      AppText.reportThisListing: 'Report this listing',
      AppText.advance: 'Advance: ',
      AppText.month: 'month',
      AppText.months: 'months',
      AppText.officeRooms: 'Office Rooms',
      AppText.rooms: 'Rooms',
      AppText.conf: 'Conf',
      AppText.sqmt: 'sqmt',
      AppText.notSpecified: 'Not Specified',
      AppText.viewDetails: 'View Details',
      AppText.perNight: ' / night',
      AppText.min: 'Min ',
      AppText.propertyCategory: 'Property Category',
      AppText.chooseFromHomeOffice:
          'Choose from: Home (residential), Office (commercial)',
      AppText.officeDetails: 'Office Details',
      AppText.specifyOfficeRooms:
          'Specify the number of office rooms, conference rooms, and workstations',
      AppText.roomsAndBathrooms: 'Rooms & Bathrooms',
      AppText.propertySizeOptional: 'Property Size (Square Meter) - Optional',
      AppText.enterPropertySize:
          'Enter property size in square meter (e.g., 1200) - Optional',
      AppText.aboutThisRental: 'About This Rental (Optional)',
      AppText.describeYourProperty:
          'Describe your property, highlight key features and what makes it special...',
      AppText.incomplete: 'Incomplete',
      AppText.pleaseFillAllRequiredFields: 'Please fill all required fields',
      AppText.chooseListingType: 'Choose Listing Type',
      AppText.selectListingType: 'Select the type of property you want to list',
      AppText.normalApartment: 'Normal Apartment',
      AppText.traditionalLongTermRental:
          'Traditional long-term rental with monthly payments',
      AppText.monthlyRentPayments: 'Monthly rent payments',
      AppText.securityDepositRequired: 'Security deposit required',
      AppText.advancePayments: 'Advance payments',
      AppText.longTermLease: 'Long-term lease',
      AppText.furnishedApartment: 'Furnished Apartment',
      AppText.shortTermDailyRental:
          'Short-term daily rental with flexible booking',
      AppText.dailyRatePricing: 'Daily rate pricing',
      AppText.flexibleCheckInOut: 'Flexible check-in/out',
      AppText.minMaxStay: 'Minimum/maximum stay',
      AppText.selectionRequired: 'Selection Required',
      AppText.pleaseSelectListingType: 'Please select a listing type',
      AppText.totalViews: 'Total Views',
      AppText.inquiries: 'Inquiries',
      AppText.activeListings: 'Active Listings',
      AppText.myProperties: 'My Properties',
      AppText.addProperty: '+ Add Property',
      AppText.noPropertiesYet: 'No Properties Yet',
      AppText.startByAddingYourFirstProperty:
          'Start by adding your first property',
      AppText.addNewProperty: 'Add New Property',
      AppText.editProperty: 'Edit Property',
      AppText.shareProperty: 'Share Property',
      AppText.deleteProperty: 'Delete Property',
      AppText.areYouSureYouWantToDelete: 'Are you sure you want to delete',
      AppText.thisActionCannotBeUndone: 'This action cannot be undone.',
      AppText.cancel: 'Cancel',
      AppText.delete: 'Delete',
      AppText.deleted: 'Deleted',
      AppText.hasBeenDeleted: 'has been deleted',
      AppText.step: 'Step',
      AppText.of: 'of',
      AppText.listingType: 'Listing Type',
      AppText.basicInformation: 'Basic Information',
      AppText.pricingAndBooking: 'Pricing & Booking',
      AppText.pricingAndTerms: 'Pricing & Terms',
      AppText.locationDetails: 'Location Details',
      AppText.amenitiesAndRules: 'Amenities & Rules',
      AppText.featuresAndAmenities: 'Features & Amenities',
      AppText.propertyPhotos: 'Property Photos',
      AppText.ownerDetails: 'Owner Details',
      AppText.dailyRate: 'Daily Rate',
      AppText.minimumStay: 'Minimum Stay',
      AppText.maximumStay: 'Maximum Stay',
      AppText.checkInTime: 'Check-in Time',
      AppText.checkOutTime: 'Check-out Time',
      AppText.pleaseCompleteThePricingAndBookingDetails:
          'Please complete the pricing & booking details',
      AppText.monthlyRent: 'Monthly Rent',
      AppText.advancePayment: 'Advance Payment',
      AppText.numberOfMonthsToBePaidInAdvance:
          'Number of months to be paid in advance',
      AppText.securityDeposit: 'Security Deposit',
      AppText.numberOfMonthsForRefundableSecurityDeposit:
          'Number of months for refundable security deposit',
      AppText.pricingTips: 'Pricing Tips',
      AppText.researchComparablePropertiesInYourArea:
          'Research comparable properties in your area',
      AppText.considerIncludingUtilitiesInRentForConvenience:
          'Consider including utilities in rent for convenience',
      AppText.beCompetitiveButFairWithYourPricing:
          'Be competitive but fair with your pricing',
      AppText.pleaseCompleteThePricingAndTermsDetails:
          'Please complete the pricing & terms details',
      AppText.cityName: 'City Name',
      AppText.selectCity: 'Select City',
      AppText.noCitiesAvailable: 'No cities available',
      AppText.neighbourhood: 'Neighbourhood',
      AppText.selectNeighbourhood: 'Select neighbourhood',
      AppText.distanceToMainRoad: 'Distance to Main Road (miles) ',
      AppText.egDistanceToMainRoad: 'e.g., 0.5 miles from main road',
      AppText.nearbyLandmarks: 'Nearby Landmarks',
      AppText.egNearbyLandmarks:
          '5 min walk to Central Park, 2 blocks from subway station...',
      AppText.pleaseProvideTheRequiredLocationDetails:
          'Please provide the required location details',
      AppText.whatsIncluded: 'What\'s Included',
      AppText.houseRules: 'House Rules',
      AppText.propertyFeatures: 'Property Features',
      AppText.buildingAmenities: 'Building Amenities',
      AppText.selectAtLeastOneFurnishingOrRule:
          'Select at least one furnishing or rule',
      AppText.selectAtLeastOneFeatureOrAmenity:
          'Select at least one feature or amenity',
      AppText.terrace: 'Terrace',
      AppText.parkingSpace: 'Parking Space',
      AppText.airConditioner: 'Air Conditioner',
      AppText.semiFurnished: 'Semi-Furnished',
      AppText.utilitiesIncluded: 'Utilities Included',
      AppText.waterIncluded: 'Water Included',
      AppText.maintenanceIncluded: 'Maintenance Included',
      AppText.furnished: 'Furnished',
      AppText.unfurnished: 'Unfurnished',
      AppText.electricityIncluded: 'Electricity Included',
      AppText.internetIncluded: 'Internet Included',
      AppText.bed: 'Bed',
      AppText.sofa: 'Sofa',
      AppText.diningTable: 'Dining Table',
      AppText.chairs: 'Chairs',
      AppText.wardrobe: 'Wardrobe',
      AppText.tv: 'TV',
      AppText.refrigerator: 'Refrigerator',
      AppText.microwave: 'Microwave',
      AppText.washingMachine: 'Washing Machine',
      AppText.wiFi: 'Wi-Fi',
      AppText.desk: 'Desk',
      AppText.kitchenUtensils: 'Kitchen Utensils',
      AppText.bedding: 'Bedding',
      AppText.towels: 'Towels',
      AppText.noSmoking: 'No Smoking',
      AppText.noPets: 'No Pets',
      AppText.noParties: 'No Parties',
      AppText.quietHours: 'Quiet Hours 10 PM - 7 AM',
      AppText.guestAllowed: 'Guest Allowed',
      AppText.suitableForChildren: 'Suitable for Children',
      AppText.suitableForInfants: 'Suitable for Infants',
      AppText.longTermStaysWelcome: 'Long-term Stays Welcome',
      AppText.addAtLeast3HighQualityPhotos:
          'Add at least 3 high-quality photos',
      AppText.addMorePhotos: 'Add More Photos',
      AppText.photoGuidelines: 'Photo Guidelines',
      AppText.firstPhotoWillBeTheMainListingImage:
          'First photo will be the main listing image',
      AppText.addTheRequiredPropertyPhotosBeforeContinuing:
          'Add the required property photos before continuing',
      AppText.previous: 'Previous',
      AppText.publishProperty: 'Publish Property',
      AppText.landlordLoyaltyCreditProgram: 'Landlord Loyalty Credit Program',
      AppText.landlordLoyaltyCreditProgramTerms:
          'By publishing this property, you agree to the terms of our '
          'Landlord Loyalty Credit Program:\n\n'
          '• You will earn a loyalty credit equal to 30% of 80% of the monthly rent (24% of the total).\n'
          '• The credit is stored in your account immediately after publishing.\n'
          '• Once a tenant who found the property through our platform pays their fee, your credit will be released as cash or transfer.\n'
          '• If the listing is removed, the credit will be recalculated.\n\n'
          '💡 *Additional Benefit:*\n'
          'If a renter successfully completes the rental transaction using our app, '
          'you (the property owner) will also receive a percentage of the commission fee '
          'that we charge for facilitating the transaction. This ensures you share in the success '
          'of deals completed through our platform.\n\n'
          'This program is designed to reward landlords who list consistently and rent through our platform.',
      AppText.iHaveReadAndAgreeToTheLandlordLoyaltyCreditProgramTerms:
          'I have read and agree to the Landlord Loyalty Credit Program terms and owner commission benefit.',
      AppText.ownerProfile: 'Owner Profile',
      AppText.failedToLoadProfile: 'Failed to load profile',
      AppText.noProfileDataAvailable: 'No profile data available',
      AppText.switchToRenterDashboard: 'Switch to Renter Dashboard',
      AppText.editContactInformation: 'Edit Contact Information',
      AppText.location: 'Location',
      AppText.save: 'Save',
      AppText.aiAssistant: 'AI Assistant',
      AppText.yourAiAssistant: 'Your AI Assistant',
      AppText.aiAssistantDescription:
          'Using this, you can ask your questions and receive suggestions from artificial intelligence assistant',
      AppText.startYourJourney: 'Start Your Journey',
      AppText.verificationCode: 'Verification Code',
      AppText.enterCodeSentToYourPhoneNumber:
          'Enter Code Sent to Your Whatsapp Number',
      AppText.verify: 'Verify',
      AppText.resendCode: 'Resend code',
      AppText.subject: 'Subject',
      AppText.writeYourIssueTitleHere: 'Write your issue title here...',
      AppText.description: 'Description',
      AppText.pleaseDescribeYourIssueInDetail:
          'Please describe your issue in detail...',
      AppText.attachmentOptional: 'Attachment (Optional)',
      AppText.attachYourFileOrPhoto: 'Attach your file or photo',
      AppText.sendMessage: 'Send Message',
      AppText.favoritesProperties: 'Favorites Properties',
      AppText.signInToViewFavorites: 'Sign in to view favorites',
      AppText.logInToSavePropertiesAndAccessThemFromThisTab:
          'Log in to save properties and access them from this tab.',
      AppText.yourFavoritePropertyListIsEmpty:
          'Your favorite property list is empty! ',
      AppText.tapTheHeartOnAnyListingToKeepItHandyHere:
          'Tap the heart on any listing to keep it handy here.',
      AppText.furnishedApartments: 'Furnished Apartments',
      AppText.resetFilters: 'Reset Filters',
      AppText.propertyNotFound: 'Property Not Found',
      AppText.filters: 'Filters',
      AppText.reset: 'Reset',
      AppText.availableDates: 'Available Dates',
      AppText.priceRange: 'Price Range',
      AppText.minPrice: 'Min Price',
      AppText.maxPrice: 'Max Price',
      AppText.bathrooms: 'Bathrooms',
      AppText.neighborhoods: 'Neighborhoods',
      AppText.chooseNeighborhoods: 'Choose neighborhoods',
      AppText.showProperties: 'Show Properties',
      AppText.checkIn: 'Check-in',
      AppText.selectDate: 'Select date',
      AppText.checkOut: 'Check-out',
      AppText.night: 'night',
      AppText.nights: 'nights',
      AppText.selectCheckInDate: 'Select Check-in Date',
      AppText.pleaseSelectACheckInDateFirst:
          'Please select a check-in date first',
      AppText.filterApartments: 'Filter Apartments',
      AppText.clearAll: 'Clear All',
      AppText.propertyType: 'Property Type',
      AppText.all: 'All',
      AppText.home: 'Home',
      AppText.office: 'Office',
      AppText.city: 'City',
      AppText.downtown: 'Downtown',
      AppText.uptown: 'Uptown',
      AppText.suburbs: 'Suburbs',
      AppText.cityCenter: 'City Center',
      AppText.outskirts: 'Outskirts',
      AppText.residentialArea: 'Residential Area',
      AppText.kacyiru: 'Kacyiru',
      AppText.kimihurura: 'Kimihurura',
      AppText.remera: 'Remera',
      AppText.nyarutarama: 'Nyarutarama',
      AppText.gikondo: 'Gikondo',
      AppText.kicukiro: 'Kicukiro',
      AppText.nyarugenge: 'Nyarugenge',
      AppText.gisozi: 'Gisozi',
      AppText.bedroomsAndBathrooms: 'Bedrooms & Bathrooms',
      AppText.bedrooms: 'Bedrooms',
      AppText.any: 'Any',
      AppText.singleRoom: 'Single Room',
      AppText.singleModernRoom: 'Single Modern Room',
      AppText.studio: 'Studio',
      AppText.oneBedroom: '1 Bedroom',
      AppText.twoBedrooms: '2 Bedrooms',
      AppText.threePlusBedrooms: '3+ Bedrooms',
      AppText.one: '1',
      AppText.two: '2',
      AppText.three: '3',
      AppText.fourPlus: '4+',
      AppText.bikePriceFromMainRoad: 'Bike Price From Main Road',
      AppText.paymentTerms: 'Payment Terms',
      AppText.advancePaymentMonths: 'Advance Payment (Months)',
      AppText.oneMonth: '1 Month',
      AppText.twoMonths: '2 Months',
      AppText.threeMonths: '3 Months',
      AppText.sixMonths: '6 Months',
      AppText.twelveMonths: '12 Months',
      AppText.securityDepositMonths: 'Security Deposit (Months)',
      AppText.applyFilters: 'Apply Filters',
      // AppText.propertyLocation: 'Property Location',
      AppText.noApartmentsFound: 'No apartments found',
      AppText.activeFiltersApplied: 'Active filters applied',
      AppText.myProfile: 'My Profile',
      AppText.edit: 'Edit',
      AppText.name: 'Name',
      AppText.enterName: 'Enter name',
      AppText.enterPhoneNumber: 'Enter phone number',
      AppText.email: 'Email',
      AppText.enterEmailAddress: 'Enter email address',
      AppText.faqs: 'FAQs',
      AppText.faqQuestion1:
          'How to search rental properties in a specific area?',
      AppText.faqAnswer1:
          'Use the search bar on the home page to filter by city, state, or region.',
      AppText.faqQuestion2: 'How do I contact the property owner or manager?',
      AppText.faqAnswer2:
          'Once you find a property you like, tap Contact to send a message or call the owner directly.',
      AppText.faqQuestion3: 'Can I schedule a viewing via the app?',
      AppText.faqAnswer3:
          'Yes. Many listings allow you to request a viewing directly from the property details page.',
      AppText.faqQuestion4: 'Is it safe to make payments through the app?',
      AppText.faqAnswer4:
          'If the app supports online payments, those flows are encrypted and secured for transactions. Always confirm with the property owner.',
      AppText.faqQuestion5: 'How do I contact a property owner?',
      AppText.faqAnswer5:
          'Open the listing and tap the Contact Owner button to message or call.',
      AppText.faqQuestion6: 'How can I save properties to view later?',
      AppText.faqAnswer6:
          'Tap the heart icon on a property to add it to your saved list. Sign in to sync across devices.',
      AppText.faqQuestion7:
          'Can I filter properties by price, size and amenities?',
      AppText.faqAnswer7:
          'Yes — open the filter panel and set price range, size, and other options to narrow results.',
      AppText.faqQuestion8: 'How do I report an incorrect listing?',
      AppText.faqAnswer8:
          'Open the listing, tap the menu (three dots) and choose "Report" to flag issues to our team.',
      AppText.faqQuestion9: 'What payment methods are supported?',
      AppText.faqAnswer9:
          'Payment methods vary by landlord. Check the listing or contact the owner for supported options.',
      AppText.faqQuestion10: 'How do I change my language or locale?',
      AppText.faqAnswer10:
          'Go to Settings → Language and select your preferred language.',
      AppText.furnishedApartmentDetails: 'Furnished Apartment Details',
      AppText.cancellationPolicy: 'Cancellation Policy',
      AppText.furnishingsIncluded: 'Furnishings Included',
      AppText.hintText: 'Search in state, city, region...',
      AppText.filter: 'Filter',
      AppText.navbarHome: 'Home',
      AppText.navbarFavorites: 'Favorites',
      AppText.navbarAI: 'AI',
      AppText.navbarProfile: 'Profile',
      AppText.navbarMenu: 'Menu',
      AppText.contactInformation: 'Contact Information',
      AppText.viewingRequests: 'Viewing Requests',
      AppText.propertyUpdates: 'Property Updates',
      AppText.viewingRequestsDetails: 'Get notified of new viewing requests',
      AppText.propertyUpdatesDetails: 'Status changes and approvals',
      AppText.propertyOwner: 'Property Owner',
      AppText.propertyDetails: 'Property Details',
      AppText.managePropertyAvailability: 'Manage Property Availability',
      AppText.booked: 'Booked',
      AppText.available: 'Available',
      AppText.selectedDatesToBlock: 'Selected Dates to Block',
      AppText.clearSelection: 'Clear Selection',
      AppText.markAsBooked: 'Mark as Booked',
      AppText.success: 'Success',
      AppText.datesMarkedAsBooked: 'Dates marked as booked',
      AppText.datesSelected: 'Dates selected',
      AppText.sun: 'Sun',
      AppText.mon: 'Mon',
      AppText.tue: 'Tue',
      AppText.wed: 'Wed',
      AppText.thu: 'Thu',
      AppText.fri: 'Fri',
      AppText.sat: 'Sat',
      AppText.chooseAnOption: 'Choose an option',
      AppText.phoneCall: 'Phone Call',
      AppText.whatsapp: 'WhatsApp',
      AppText.directCallToOwner: 'Direct Call to Owner',
      AppText.sendInstantMessage: 'Send Instant Message',
      AppText.logout: 'Logout',
      AppText.done: 'Done',
      AppText.needHelp: 'Need Help?',
      AppText.contactSupportViaWhatsApp: 'Contact Support via WhatsApp',
      AppText.supportAvailability:
          'Our support team is available 24/7 to assist you with any inquiries or issues you may have.',
      AppText.confirmLogout: 'Are you sure you want to logout?',
      AppText.continueText: 'Continue',
      AppText.beforeContinue: 'Before You Continue',
      AppText.continueToWhatsApp:
          'You are about to contact the property owner via WhatsApp.',
      AppText.safetyText:
          'For your safety, please make sure all rental agreements are completed inside our app/company platform.',
      AppText.normalApartmentsAreComingSoon:
          'Normal Apartments Are Coming Soon',
      AppText.normalApartmentsPrepare:
          'We’re currently preparing the best long-term rental options for you. Please check back shortly!',
      AppText.pleaseEnterYourName: 'Please enter your name',
      AppText.pleaseEnterYourEmail: 'Please enter your email',
      AppText.numberCantChange: 'Phone number cannot be changed',
      AppText.homeTypeProperty: 'Home',
      AppText.officeTypeProperty: 'Office',
      AppText.propertyOwnerDetails: 'Property Owner Details',
      AppText.ownerName: 'Owner Name',
      AppText.enterYourFullName: 'Enter your full name',
      AppText.ownerPhoneNumber: 'Owner Phone Number',
      AppText.enterOwnerPhoneNumber: 'Phone number',
      AppText.referenceContactFurnished: 'Reference Contact (Optional)',
      AppText.referenceContactMandatory: 'Reference Contact (Mandatory)',
      AppText.provideAtLeastOnePersonWhoCanVerify:
          'Provide at least one person who can verify property information',
      AppText.relationship: 'Relationship',
      AppText.addAnotherReferenceOptional: 'Add Another Reference (Optional)',
      AppText.additionalReferenceOptional: 'Additional Reference (Optional)',
      AppText.reference: 'Reference',
      AppText.optional: 'Optional',

      AppText.neighbour: 'Neighbour',
      AppText.previousTenant: 'Previous Tenant',
      AppText.localContact: 'Local Contact',
      AppText.friend: 'Friend',
      AppText.relative: 'Relative',
      AppText.caretaker: 'Caretaker',
      AppText.societyMember: 'Society Member',
      AppText.other: 'Other',
      AppText.next: 'Next',
    },

    'fr_FR': {
      AppText.phoneNumber: 'Numéro de téléphone',
      AppText.logIn: 'Se connecter',
      AppText.createAccount: 'Créer un compte',
      AppText.dontHaveAnAccount: "Vous n'avez pas de compte ? ",
      AppText.alreadyHaveAnAccount: "Vous avez déjà un compte ? ",
      AppText.signUp: "S'inscrire",
      AppText.signIn: 'Se connecter',
      AppText.settings: 'Paramètres',
      AppText.switchToOwnersDashboard:
          'Passer au tableau de bord des propriétaires',
      AppText.profile: 'Profil',
      AppText.language: 'Langue',
      AppText.notificationSettings: 'Paramètres de notification',
      AppText.contactUs: 'Contactez-nous',
      AppText.faq: 'FAQ',
      AppText.goodMorning: 'Bonjour!',
      AppText.noFurnishedApartmentsFound: 'Aucun appartement meublé trouvé',
      AppText.tryAdjustingYourFilters: 'Essayez de régler vos filtres',
      AppText.normalApartments: 'Location longue durée',
      AppText.longTermRentals: 'Locations à long terme',
      AppText.monthlyPayments: 'Paiements mensuels',
      AppText.homeAndOfficeSpaces: 'Espaces de maison et de bureau',
      AppText.explore: 'Explorer',
      AppText.logInToGetAccess:
          'Connectez-vous pour accéder à toutes les fonctionnalités',
      AppText.haventAccountAlready: "Vous n'avez pas encore de compte ?",
      AppText.createAnAccount: 'Créer un compte',
      AppText.unableToLoadProfile: 'Impossible de charger le profil',
      AppText.retry: 'Réessayer',
      AppText.noProfileInfoAvailable: 'Aucune information de profil disponible',
      AppText.referenceContacts: 'Contacts de référence',
      AppText.contactName: 'Nom du contact',
      AppText.primaryContact: 'Contact principal',
      AppText.contactOwner: 'Contacter le propriétaire',
      AppText.iWantToRent: 'Je veux louer',
      AppText.reportThisListing: 'Signaler cette annonce',
      AppText.advance: 'Avance: ',
      AppText.month: 'mois',
      AppText.months: 'mois',
      AppText.officeRooms: 'Salles de bureau',
      AppText.rooms: 'Pièces',
      AppText.conf: 'Conf',
      AppText.sqmt: 'm²',
      AppText.notSpecified: 'Non spécifié',
      AppText.viewDetails: 'Voir les détails',
      AppText.perNight: ' / nuit',
      AppText.min: 'Min ',
      AppText.basicInformation: 'Informations de base',
      AppText.propertyCategory: 'Catégorie de propriété',
      AppText.chooseFromHomeOffice:
          'Choisissez parmi : Maison (résidentiel), Bureau (commercial)',
      AppText.officeDetails: 'Détails du bureau',
      AppText.specifyOfficeRooms:
          'Spécifiez le nombre de bureaux, de salles de conférence et de postes de travail',
      AppText.roomsAndBathrooms: 'Pièces et salles de bain',
      AppText.propertySizeOptional:
          'Taille de la propriété (mètre carré) - Facultatif',
      AppText.enterPropertySize:
          'Entrez la taille de la propriété en mètres carrés (par exemple, 1200) - Facultatif',
      AppText.aboutThisRental: 'À propos de cette location (Facultatif)',
      AppText.describeYourProperty:
          'Décrivez votre propriété, mettez en évidence les principales caractéristiques et ce qui la rend spéciale...',
      AppText.incomplete: 'Incomplet',
      AppText.pleaseFillAllRequiredFields:
          'Veuillez remplir tous les champs obligatoires',
      AppText.chooseListingType: 'Choisissez le type d\'annonce',
      AppText.selectListingType:
          'Sélectionnez le type de propriété que vous souhaitez répertorier',
      AppText.normalApartment: 'Location longue durée',
      AppText.traditionalLongTermRental:
          'Location longue durée traditionnelle avec paiements mensuels',
      AppText.monthlyRentPayments: 'Paiements de loyer mensuels',
      AppText.securityDepositRequired: 'Dépôt de garantie requis',
      AppText.advancePayments: 'Paiements anticipés',
      AppText.longTermLease: 'Bail à long terme',
      AppText.furnishedApartment: 'Appartement meublé',
      AppText.shortTermDailyRental:
          'Location journalière à court terme avec réservation flexible',
      AppText.dailyRatePricing: 'Tarification journalière',
      AppText.flexibleCheckInOut: 'Enregistrement/départ flexible',
      AppText.minMaxStay: 'Séjour minimum/maximum',
      AppText.selectionRequired: 'Sélection requise',
      AppText.pleaseSelectListingType:
          'Veuillez sélectionner un type d\'annonce',
      AppText.totalViews: 'Vues totales',
      AppText.inquiries: 'Demandes',
      AppText.activeListings: 'Annonces actives',
      AppText.myProperties: 'Mes propriétés',
      AppText.addProperty: '+ Ajouter une propriété',
      AppText.noPropertiesYet: 'Aucune propriété pour le moment',
      AppText.startByAddingYourFirstProperty:
          'Commencez par ajouter votre première propriété',
      AppText.addNewProperty: 'Ajouter une nouvelle propriété',
      AppText.editProperty: 'Modifier la propriété',
      AppText.shareProperty: 'Partager la propriété',
      AppText.deleteProperty: 'Supprimer la propriété',
      AppText.areYouSureYouWantToDelete: 'Êtes-vous sûr de vouloir supprimer',
      AppText.thisActionCannotBeUndone:
          'Cette action ne peut pas être annulée.',
      AppText.cancel: 'Annuler',
      AppText.delete: 'Supprimer',
      AppText.deleted: 'Supprimé',
      AppText.hasBeenDeleted: 'a été supprimé',
      AppText.step: 'Étape',
      AppText.of: 'de',
      AppText.listingType: 'Type d\'annonce',
      AppText.pricingAndBooking: 'Tarifs et réservation',
      AppText.pricingAndTerms: 'Tarifs et conditions',
      AppText.locationDetails: 'Détails de l\'emplacement',
      AppText.amenitiesAndRules: 'Équipements et règles',
      AppText.featuresAndAmenities: 'Caractéristiques et équipements',
      AppText.propertyPhotos: 'Photos de la propriété',
      AppText.ownerDetails: 'Détails du propriétaire',
      AppText.dailyRate: 'Tarif journalier',
      AppText.minimumStay: 'Séjour minimum',
      AppText.maximumStay: 'Séjour maximum',
      AppText.checkInTime: 'Heure d\'arrivée',
      AppText.checkOutTime: 'Heure de départ',
      AppText.pleaseCompleteThePricingAndBookingDetails:
          'Veuillez compléter les détails de tarification et de réservation',
      AppText.monthlyRent: 'Loyer mensuel',
      AppText.advancePayment: 'Paiement anticipé',
      AppText.numberOfMonthsToBePaidInAdvance:
          'Nombre de mois à payer à l\'avance',
      AppText.securityDeposit: 'Dépôt de garantie',
      AppText.numberOfMonthsForRefundableSecurityDeposit:
          'Nombre de mois pour le dépôt de garantie remboursable',
      AppText.pricingTips: 'Conseils de tarification',
      AppText.researchComparablePropertiesInYourArea:
          'Recherchez des propriétés comparables dans votre région',
      AppText.considerIncludingUtilitiesInRentForConvenience:
          'Envisagez d\'inclure les services publics dans le loyer pour plus de commodité',
      AppText.beCompetitiveButFairWithYourPricing:
          'Soyez compétitif mais juste avec vos tarifs',
      AppText.pleaseCompleteThePricingAndTermsDetails:
          'Veuillez compléter les détails de tarification et de conditions',
      AppText.cityName: 'Nom de la ville',
      AppText.selectCity: 'Sélectionnez la ville',
      AppText.noCitiesAvailable: 'Aucune ville disponible',
      AppText.neighbourhood: 'Quartier',
      AppText.selectNeighbourhood: 'Sélectionnez le quartier',
      AppText.distanceToMainRoad: 'Distance de la route principale (mètres)',
      AppText.egDistanceToMainRoad:
          'par exemple, à 100 mètres de la route principale',
      AppText.nearbyLandmarks: 'Points d\'intérêt à proximité',
      AppText.egNearbyLandmarks:
          '5 min à pied de Central Park, à 2 pâtés de maisons de la station de métro...',
      AppText.pleaseProvideTheRequiredLocationDetails:
          'Veuillez fournir les détails de l\'emplacement requis',
      AppText.whatsIncluded: 'Ce qui est inclus',
      AppText.houseRules: 'Règles',
      AppText.propertyFeatures: 'Caractéristiques de la propriété',
      AppText.buildingAmenities: 'Équipements du bâtiment',
      AppText.selectAtLeastOneFurnishingOrRule:
          'Sélectionnez au moins un ameublement ou une règle',
      AppText.selectAtLeastOneFeatureOrAmenity:
          'Sélectionnez au moins une caractéristique ou un équipement',
      AppText.terrace: 'Terrasse',
      AppText.parkingSpace: 'Place de parking',
      AppText.airConditioner: 'Climatiseur',
      AppText.semiFurnished: 'Semi-meublé',
      AppText.utilitiesIncluded: 'Services publics inclus',
      AppText.waterIncluded: 'Eau incluse',
      AppText.maintenanceIncluded: 'Entretien inclus',
      AppText.furnished: 'Meublé',
      AppText.unfurnished: 'Non meublé',
      AppText.electricityIncluded: 'Électricité incluse',
      AppText.internetIncluded: 'Internet inclus',
      AppText.bed: 'Lit',
      AppText.sofa: 'Canapé',
      AppText.diningTable: 'Table à manger',
      AppText.chairs: 'Chaises',
      AppText.wardrobe: 'Armoire',
      AppText.tv: 'la télé',
      AppText.refrigerator: 'Réfrigérateur',
      AppText.microwave: 'Four micro onde',
      AppText.washingMachine: 'Machine à laver',
      AppText.wiFi: 'Wifi',
      AppText.desk: 'Bureau',
      AppText.kitchenUtensils: 'Ustensiles de cuisine',
      AppText.bedding: 'Literie',
      AppText.towels: 'Les serviettes',
      AppText.noSmoking: 'Interdiction de fumer',
      AppText.noPets: 'Animaux interdits',
      AppText.noParties: 'Pas de fêtes',
      AppText.quietHours: 'Heures calmes 22h - 7h',
      AppText.guestAllowed: 'Invité autorisé',
      AppText.suitableForChildren: 'Convient aux enfants',
      AppText.suitableForInfants: 'Convient aux nourrissons',
      AppText.longTermStaysWelcome: 'Longs séjours bienvenus',
      AppText.addAtLeast3HighQualityPhotos:
          'Ajoutez au moins 3 photos de haute qualité',
      AppText.addMorePhotos: 'Ajouter plus de photos',
      AppText.photoGuidelines: 'Directives pour les photos',
      AppText.firstPhotoWillBeTheMainListingImage:
          'La première photo sera l\'image principale de l\'annonce',
      AppText.addTheRequiredPropertyPhotosBeforeContinuing:
          'Ajoutez les photos de propriété requises avant de continuer',
      AppText.previous: 'Précédent',
      AppText.publishProperty: 'Publier la propriété',
      AppText.landlordLoyaltyCreditProgram:
          'Programme de crédit de fidélité du propriétaire',
      AppText.landlordLoyaltyCreditProgramTerms:
          'En publiant cette propriété, vous acceptez les termes de notre programme de crédit de fidélité du propriétaire:\n\n'
          '• Vous gagnerez un crédit de fidélité égal à 30% de 80% du loyer mensuel (24% du total).\n'
          '• Le crédit est stocké dans votre compte immédiatement après la publication.\n'
          '• Une fois qu\'un locataire qui a trouvé la propriété via notre plateforme paie ses frais, votre crédit sera libéré en espèces ou par virement.\n'
          '• Si l\'annonce est supprimée, le crédit sera recalculé.\n\n'
          '💡 *Avantage supplémentaire:*\n'
          'Si un locataire effectue avec succès la transaction de location à l\'aide de notre application, '
          'vous (le propriétaire) recevrez également un pourcentage des frais de commission que nous facturons pour faciliter la transaction. Cela garantit que vous partagez le succès des transactions conclues via notre plateforme.\n\n'
          'Ce programme est conçu pour récompenser les propriétaires qui publient régulièrement et louent via notre plateforme.',
      AppText.iHaveReadAndAgreeToTheLandlordLoyaltyCreditProgramTerms:
          'J\'ai lu et j\'accepte les termes du programme de crédit de fidélité du propriétaire et l\'avantage de la commission du propriétaire.',
      AppText.ownerProfile: 'Profil du propriétaire',
      AppText.failedToLoadProfile: 'Échec du chargement du profil',
      AppText.noProfileDataAvailable: 'Aucune donnée de profil disponible',
      AppText.switchToRenterDashboard: 'Passer au tableau de bord du locataire',
      AppText.editContactInformation: 'Modifier les informations de contact',
      AppText.location: 'Emplacement',
      AppText.save: 'Enregistrer',
      AppText.aiAssistant: 'Assistant IA',
      AppText.yourAiAssistant: 'Votre assistant IA',
      AppText.aiAssistantDescription:
          'En utilisant cela, vous pouvez poser vos questions et recevoir des suggestions de l\'assistant d\'intelligence artificielle',
      AppText.startYourJourney: 'Commencez votre voyage',
      AppText.verificationCode: 'Code de vérification',
      AppText.enterCodeSentToYourPhoneNumber:
          'Entrez le code envoyé à votre numéro WhatsApp',
      AppText.verify: 'Vérifier',
      AppText.resendCode: 'Renvoyer le code',
      AppText.subject: 'Sujet',
      AppText.writeYourIssueTitleHere:
          'Écrivez le titre de votre problème ici...',
      AppText.description: 'La description',
      AppText.pleaseDescribeYourIssueInDetail:
          'Veuillez décrire votre problème en détail...',
      AppText.attachmentOptional: 'Pièce jointe (facultatif)',
      AppText.attachYourFileOrPhoto: 'Joignez votre fichier ou photo',
      AppText.sendMessage: 'Envoyer le message',
      AppText.favoritesProperties: 'Propriétés favorites',
      AppText.signInToViewFavorites: 'Connectez-vous pour voir les favoris',
      AppText.logInToSavePropertiesAndAccessThemFromThisTab:
          'Connectez-vous pour enregistrer les propriétés et y accéder depuis cet onglet.',
      AppText.yourFavoritePropertyListIsEmpty:
          'Votre liste de propriétés préférées est vide ! ',
      AppText.tapTheHeartOnAnyListingToKeepItHandyHere:
          'Appuyez sur le cœur de n\'importe quelle annonce pour la garder à portée de main ici.',
      AppText.furnishedApartments: 'Appartements meublés',
      AppText.resetFilters: 'Réinitialiser les filtres',
      AppText.propertyNotFound: 'Propriété introuvable',
      AppText.filters: 'Filtres',
      AppText.reset: 'Réinitialiser',
      AppText.availableDates: 'Dates disponibles',
      AppText.priceRange: 'Fourchette de prix',
      AppText.minPrice: 'Prix min',
      AppText.maxPrice: 'Prix max',
      AppText.bathrooms: 'Salles de bain',
      AppText.neighborhoods: 'Quartiers',
      AppText.chooseNeighborhoods: 'Choisir les quartiers',
      AppText.showProperties: 'Afficher les propriétés',
      AppText.checkIn: 'Arrivée',
      AppText.selectDate: 'Sélectionner la date',
      AppText.checkOut: 'Départ',
      AppText.night: 'nuit',
      AppText.nights: 'nuits',
      AppText.selectCheckInDate: 'Sélectionner la date d\'arrivée',
      AppText.pleaseSelectACheckInDateFirst:
          'Veuillez sélectionner une date d\'arrivée d\'abord',
      AppText.filterApartments: 'Filtrer les appartements',
      AppText.clearAll: 'Tout effacer',
      AppText.propertyType: 'Type de propriété',
      AppText.all: 'Tout',
      AppText.home: 'Maison',
      AppText.office: 'Bureau',
      AppText.city: 'Ville',
      AppText.downtown: 'Centre-ville',
      AppText.uptown: 'Haut de la ville',
      AppText.suburbs: 'Banlieues',
      AppText.cityCenter: 'Centre-ville',
      AppText.outskirts: 'Périphérie',
      AppText.residentialArea: 'Zone résidentielle',
      AppText.kacyiru: 'Kacyiru',
      AppText.kimihurura: 'Kimihurura',
      AppText.remera: 'Remera',
      AppText.nyarutarama: 'Nyarutarama',
      AppText.gikondo: 'Gikondo',
      AppText.kicukiro: 'Kicukiro',
      AppText.nyarugenge: 'Nyarugenge',
      AppText.gisozi: 'Gisozi',
      AppText.bedroomsAndBathrooms: 'Chambres et salles de bain',
      AppText.bedrooms: 'Chambres',
      AppText.any: 'N\'importe lequel',
      AppText.singleRoom: 'Chambre simple',
      AppText.singleModernRoom: 'Chambre moderne simple',
      AppText.studio: 'Studio',
      AppText.oneBedroom: '1 Chambre',
      AppText.twoBedrooms: '2 Chambres',
      AppText.threePlusBedrooms: '3+ Chambres',
      AppText.one: '1',
      AppText.two: '2',
      AppText.three: '3',
      AppText.fourPlus: '4+',
      AppText.bikePriceFromMainRoad: 'Prix du vélo de la route principale',
      AppText.paymentTerms: 'Modalités de paiement',
      AppText.advancePaymentMonths: 'Paiement anticipé (mois)',
      AppText.oneMonth: '1 mois',
      AppText.twoMonths: '2 mois',
      AppText.threeMonths: '3 mois',
      AppText.sixMonths: '6 mois',
      AppText.twelveMonths: '12 mois',
      AppText.securityDepositMonths: 'Dépôt de garantie (mois)',
      AppText.applyFilters: 'Appliquer les filtres',
      AppText.noApartmentsFound: 'Aucun appartement trouvé',
      AppText.activeFiltersApplied: 'Filtres actifs appliqués',
      AppText.myProfile: 'Mon profil',
      AppText.edit: 'Modifier',
      AppText.name: 'Nom',
      AppText.enterName: 'Entrez le nom',
      AppText.enterPhoneNumber: 'Entrez le numéro de téléphone',
      AppText.email: 'E-mail',
      AppText.enterEmailAddress: 'Entrez l\'adresse e-mail',
      AppText.faqs: 'FAQ',
      AppText.faqQuestion1:
          'Comment rechercher des propriétés locatives dans une zone spécifique ?',
      AppText.faqAnswer1:
          'Vous pouvez utiliser la barre de recherche sur la page d\'accueil pour filtrer par ville, état ou région.',
      AppText.faqQuestion2:
          'Comment contacter le propriétaire ou le gestionnaire immobilier ?',
      AppText.faqAnswer2:
          'Une fois que vous avez trouvé une propriété qui vous intéresse, appuyez sur contacter pour envoyer un message directement au propriétaire.',
      AppText.faqQuestion3: 'Puis-je planifier une visite via l\'application ?',
      AppText.faqAnswer3:
          'Oui ! De nombreuses annonces vous permettent de demander une visite directement depuis la page de détails de la propriété.',
      AppText.faqQuestion4:
          'Est-il sûr d\'effectuer des paiements via l\'application ?',
      AppText.faqAnswer4:
          'Oui, si l\'application prend en charge les paiements en ligne, elle est cryptée et sécurisée pour les transactions.',
      AppText.faqQuestion5: 'Comment contacter un propriétaire ?',
      AppText.faqAnswer5:
          'Ouvrez l\'annonce et appuyez sur le bouton Contacter pour envoyer un message ou appeler.',
      AppText.faqQuestion6:
          'Comment enregistrer des propriétés pour les consulter plus tard ?',
      AppText.faqAnswer6:
          'Appuyez sur l\'icône en forme de cœur pour ajouter une propriété à vos favoris. Connectez-vous pour synchroniser entre appareils.',
      AppText.faqQuestion7:
          'Puis-je filtrer les propriétés par prix, taille et équipements ?',
      AppText.faqAnswer7:
          'Oui — ouvrez le panneau des filtres et définissez la fourchette de prix, la taille et les autres options pour affiner les résultats.',
      AppText.faqQuestion8: 'Comment signaler une annonce incorrecte ?',
      AppText.faqAnswer8:
          'Ouvrez l\'annonce, appuyez sur le menu (trois points) et choisissez "Signaler" pour signaler un problème.',
      AppText.faqQuestion9: 'Quels modes de paiement sont pris en charge ?',
      AppText.faqAnswer9:
          'Les modes de paiement varient selon le propriétaire. Vérifiez l\'annonce ou contactez le propriétaire pour connaître les options disponibles.',
      AppText.faqQuestion10: 'Comment changer la langue de l\'application ?',
      AppText.faqAnswer10:
          'Allez dans Paramètres → Langue et sélectionnez votre langue préférée.',
      AppText.selected: 'Sélectionné',
      AppText.unavailable: 'Indisponible',
      AppText.totalNights: 'Nuits totales',
      AppText.totalPrice: 'Prix total',
      AppText.clearDates: 'Effacer les dates',
      AppText.applyDates: 'Appliquer les dates',
      AppText.datesSelected: 'Dates sélectionnées',
      AppText.bookingSummaryContactOwner:
          'Faites défiler vers le bas pour voir le résumé de la réservation et contacter le propriétaire',
      AppText.unavailableDates: 'Dates indisponibles',
      AppText.unavailableDatesInSelectedRange:
          'Il y a des dates indisponibles dans la plage sélectionnée',
      AppText.minimumStayRequired: 'Séjour minimum requis',
      AppText.propertyRequiresMinimumStay:
          'Cette propriété exige un séjour minimum de',
      AppText.maximumStayExceeded: 'Séjour maximum dépassé',
      AppText.propertyAllowsMaximumStay:
          'Cette propriété permet un séjour maximum de',
      AppText.sun: 'Dim',
      AppText.mon: 'Lun',
      AppText.tue: 'Mar',
      AppText.wed: 'Mer',
      AppText.thu: 'Jeu',
      AppText.fri: 'Ven',
      AppText.sat: 'Sam',
      AppText.furnishedApartmentDetails: 'Détails de l\'appartement meublé',
      AppText.cancellationPolicy: 'Politique d\'annulation',
      AppText.furnishingsIncluded: 'Équipements',
      AppText.hintText: 'Rechercher dans l\'état, la ville, la région...',
      AppText.filter: 'Filtres',
      AppText.navbarHome: 'Accueil',
      AppText.navbarFavorites: 'Favoris',
      AppText.navbarAI: 'IA',
      AppText.navbarProfile: 'Profil',
      AppText.navbarMenu: 'Menu',
      AppText.contactInformation: 'Informations de contact',
      AppText.viewingRequests: 'Demandes de visualisation',
      AppText.propertyUpdates: 'Mises à jour de la propriété',
      AppText.viewingRequestsDetails:
          'Recevez des notifications pour les nouvelles demandes de visite',
      AppText.propertyUpdatesDetails: 'Changements de statut et approbations',
      AppText.propertyOwner: 'Propriétaire',
      AppText.propertyDetails: 'Détails de la propriété',
      AppText.managePropertyAvailability:
          'Gérer la disponibilité de la propriété',
      AppText.booked: 'Réservé',
      AppText.available: 'Disponible',
      AppText.selectedDatesToBlock: 'Dates sélectionnées à bloquer',
      AppText.clearSelection: 'Effacer la sélection',
      AppText.markAsBooked: 'Marquer comme réservé',
      AppText.success: 'Succès',
      AppText.datesMarkedAsBooked: 'dates marquées comme réservées',
      AppText.chooseAnOption: 'Choisissez une option',
      AppText.phoneCall: 'Appel téléphonique',
      AppText.whatsapp: 'WhatsApp',
      AppText.directCallToOwner: 'Appel direct au propriétaire',
      AppText.sendInstantMessage: 'Envoyer un message instantané',
      AppText.logout: 'Se déconnecter',
      AppText.done: 'Terminé',
      AppText.needHelp: 'Besoin d\'aide ?',
      AppText.contactSupportViaWhatsApp: 'Contacter le support via WhatsApp',
      AppText.supportAvailability:
          'Notre équipe de support est disponible 24h/24 et 7j/7 pour vous aider avec toutes vos questions ou problèmes.',
      AppText.confirmLogout: 'Êtes-vous sûr de vouloir vous déconnecter ?',
      AppText.continueText: 'Continuer',
      AppText.beforeContinue: 'Avant de continuer',
      AppText.continueToWhatsApp:
          'Vous êtes sur le point de contacter le propriétaire via WhatsApp.',
      AppText.safetyText:
          'Pour votre sécurité, veuillez vous assurer que tous les contrats de location sont effectués à l\'intérieur de notre application/plateforme d\'entreprise.',
      AppText.normalApartmentsAreComingSoon:
          'Les appartements normaux arrivent bientôt',
      AppText.normalApartmentsPrepare:
          'Nous préparons actuellement les meilleures options de location à long terme pour vous. Veuillez revenir bientôt !',
      AppText.pleaseEnterYourName: 'Veuillez entrer votre nom',
      AppText.pleaseEnterYourEmail: 'Veuillez entrer votre e-mail',
      AppText.numberCantChange:
          'Le numéro de téléphone ne peut pas être modifié',

      AppText.homeTypeProperty: 'Logement',
      AppText.officeTypeProperty: 'Bureau',
      AppText.propertyOwnerDetails: 'Détails du propriétaire',
      AppText.ownerName: 'Nom du propriétaire',
      AppText.enterYourFullName: 'Entrez votre nom complet',
      AppText.ownerPhoneNumber: 'Numéro de téléphone du propriétaire',
      AppText.enterOwnerPhoneNumber: 'Numéro de téléphone',
      AppText.referenceContactFurnished: 'Contact de référence (facultatif)',
      AppText.referenceContactMandatory: 'Contact de référence (obligatoire)',
      AppText.provideAtLeastOnePersonWhoCanVerify:
          'Fournissez au moins une personne qui peut vérifier les informations sur la propriété',
      AppText.relationship: 'Relation',
      AppText.addAnotherReferenceOptional:
          'Ajouter une autre référence (facultatif)',
      AppText.additionalReferenceOptional:
          'Référence supplémentaire (facultatif)',
      AppText.reference: 'Référence',
      AppText.neighbour: 'Voisin',
      AppText.previousTenant: 'Ancien Locataire',
      AppText.localContact: 'Contact Local',
      AppText.friend: 'Ami',
      AppText.relative: 'Parent',
      AppText.caretaker: 'Gardien',
      AppText.societyMember: 'Membre de la Société',
      AppText.other: 'Autre',
      AppText.optional: 'Facultatif',
      AppText.next: 'Suivant',
    },
  };
}
